name: mdner
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - setuptools
  - wheel
  - jupyterlab=3
  - pyyaml
  # linters and more
  - pylint
  - pycodestyle
  - pydocstyle
  - black
  # Parquet tools
  - parquet-tools
  - pip:
      - cupy-cuda12x
      - spacy[cuda12x,transformers,lookups]
      - transformers
      - sentencepiece
      - scikit-learn
      - torch
      - watermark
      - tqdm
      - matplotlib
      - seaborn
      - streamlit
      - numba
      - protobuf==3.20.*
