name: mdner
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.10 # 3.11
  - pip
  - setuptools
  - wheel
  - jupyterlab=3
  - pyyaml
  - cupy
  # linters and more
  - pylint
  - pycodestyle
  - pydocstyle
  - black
  # Parquet tools
  - parquet-tools
  - pip:
      - spacy[transformers,lookups]
      - transformers
      - sentencepiece
      - scikit-learn
      - torch
      - watermark
      - tqdm
      - matplotlib
      - seaborn
      - streamlit
      - numba
      - protobuf==3.20.*
      # For cosinus similarity analysis
      - sentence-transformers
      # For grammatical error analysis
      - language_tool_python
