name: mdner
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest priority
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - setuptools
  - wheel
  - jupyterlab=3
  - pyyaml
  - cupy
  - matplotlib
  - seaborn
  # linters and formaters
  - pydocstyle
  - black
  - ruff
  # Parquet tools
  - parquet-tools
  - pip:
      - spacy[transformers,lookups]
      - transformers
      - sentencepiece
      - scikit-learn
      - torch
      - watermark
      - tqdm
      - streamlit
      - numba
      - protobuf==3.20.*
      # For cosinus similarity analysis
      - sentence_transformers
      # For grammatical error analysis
      - language_tool_python
